language: generic
sudo: required

services:
    - docker

before_install:
    - docker build -t marcosjampietri/andrea-nextjs -f ./client/Dockerfile.dev ./client

# script:
#     - docker run -e CI=true marcosjampietri/andrea-nextjs npm test

after_success:
    - docker build -t marcosjampietri/andrea-client ./client
    - docker build -t marcosjampietri/andrea-nginx ./nginx
    - docker build -t marcosjampietri/andrea-server ./server

    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    - docker push marcosjampietri/andrea-client
    - docker push marcosjampietri/andrea-nginx
    - docker push marcosjampietri/andrea-server

deploy:
    skip_cleanup: true
    provider: elasticbeanstalk
    region: eu-west-2
    app: andrea-mangiacavallo
    env: Devopsmarcos-env
    bucket_name: elasticbeanstalk-eu-west-2-344999520177
    bucket_path: andrea-mangiacavallo
    on:
        branch: main
    access_key_id: "$AWS_ACCESS_KEY_ID"
    secret_access_key: "$AWS_SECRET_ACCESS_KEY"
